# Generated by Django 3.2.6 on 2021-11-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_players',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
