# Generated by Django 3.2.6 on 2021-11-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0002_team_players_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='user',
        ),
        migrations.AddField(
            model_name='teams',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
