# Generated by Django 3.2.6 on 2021-11-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_1', models.TextField(max_length=255)),
                ('country_2', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField()),
                ('name', models.TextField(max_length=255)),
                ('category', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'Players',
            },
        ),
    ]
