# Generated by Django 3.2.6 on 2021-11-10 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_1', models.TextField(max_length=255)),
                ('country_2', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('recorded', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('category', models.TextField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_user.country')),
            ],
            options={
                'db_table': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Player_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField(max_length=40)),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('catches', models.IntegerField()),
                ('stumps', models.IntegerField()),
                ('total', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_user.country')),
                ('matches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_user.matches')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_user.players')),
            ],
            options={
                'db_table': 'Player_score',
            },
        ),
    ]
