# Generated by Django 3.2.6 on 2021-10-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
