# Generated by Django 3.2.6 on 2021-11-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_user', '0002_matches_recorded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('country_id', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('catches', models.IntegerField()),
                ('stumps', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'Player_score',
            },
        ),
    ]
